/**
 * This file contains data arrays for the address generator script.
 * It uses the CommonJS module system to export the variables.
 */

const FIRST_NAMES = [
    "James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael",
    "Linda", "William", "Elizabeth", "David", "Barbara", "Richard", "Susan",
    "Joseph", "Jessica", "Thomas", "Sarah", "Charles", "Karen", "Christopher",
    "Nancy", "Daniel", "Lisa", "Matthew", "Betty", "Anthony", "Dorothy",
    "Donald", "Sandra", "Mark", "Ashley", "Paul", "Kimberly", "Steven",
    "Donna", "Kenneth", "Emily", "Andrew", "Michelle", "Joshua", "Carol",
    "Kevin", "Amanda", "Brian", "Melissa", "George", "Deborah", "Edward",
    "Stephanie", "Ronald", "Rebecca", "Timothy", "Laura", "Jason", "Sharon",
    "Jeffrey", "Cynthia", "Ryan", "Kathleen", "Jacob", "Helen", "Gary",
    "Amy", "Nicholas", "Shirley", "Eric", "Angela", "Jonathan", "Anna",
    "Stephen", "Brenda", "Larry", "Emma", "Justin", "Zoe", "Scott", "Sophie",
    "Brandon", "Shirley", "Benjamin", "Ruth", "Samuel", "Megan", "Frank",
    "Nicole", "Gregory", "Alice", "Raymond", "Jacqueline", "Alexander",
    "Martha", "Patrick", "Cheryl", "Jack", "Catherine", "Dennis", "Janet",
    "Jerry", "Madison", "Tyler", "Abigail", "Aaron", "Charlotte", "Jose",
    "Teresa", "Nathan", "Rose", "Henry", "Olivia", "Douglas", "Joyce"
];

const LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
    "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark",
    "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King",
    "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green",
    "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell",
    "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz",
    "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris",
    "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan",
    "Cooper", "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos",
    "Kim", "Cox", "Ward", "Richardson", "Watson", "Brooks", "Chavez",
    "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes",
    "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long",
    "Ross", "Foster", "Jimenez", "Powell", "Jenkins", "Perry"
];

const STREET_NAMES = [
    "SW Morrison St", "SW Yamhill St", "SW Alder St", "SW Washington St",
    "SW Stark St", "SW Oak St", "SW Pine St", "SW Burnside St", "SW Ankeny St",
    "SW Harvey Milk St", "SW 3rd Ave", "SW 4th Ave", "SW 5th Ave", "SW 6th Ave",
    "SW 10th Ave", "SW 11th Ave", "SW 12th Ave", "SW 13th Ave", "SW Park Ave",
    "SW 9th Ave", "SW Broadway", "SW Salmon St", "SW Taylor St", "SW Jefferson St",
    "SW Columbia St", "SW Clay St", "SW Market St", "SW Montgomery St", "SW Mill St",
    "SW Gaines St", "SW Hooker St", "SW Porter St", "SW Sherman St", "SW Arthur St",
    "SW Kelly Ave", "SW Patton Ave", "SW Condor Ave", "SW 49th Ave", "SW 50th Ave",
    "SW 51st Ave", "SW 52nd Ave", "SW 53rd Ave", "SW 54th Ave", "SW 55th Ave",
    "SW 56th Ave", "SW 57th Ave", "SW 58th Ave", "SW 59th Ave", "SW 60th Ave",
    "SW 61st Ave", "SW 62nd Ave", "SW 63rd Ave", "SW 64th Ave", "SW 65th Ave",
    "SW 66th Ave", "SW 67th Ave", "SW 68th Ave", "SW 69th Ave", "SW 70th Ave",
    "SW 71st Ave", "SW 72nd Ave", "SW 73rd Ave", "SW 74th Ave", "SW 75th Ave",
    "SW 76th Ave", "SW 77th Ave", "SW 78th Ave", "SW 79th Ave", "SW 80th Ave",
    "SW 81st Ave", "SW 82nd Ave", "SW 83rd Ave", "SW 84th Ave", "SW 85th Ave",
    "SW 86th Ave", "SW 87th Ave", "SW 88th Ave", "SW 89th Ave", "SW 90th Ave",
    "SW 91st Ave", "SW 92nd Ave", "SW 93rd Ave", "SW 94th Ave", "SW 95th Ave",
    "SW 96th Ave", "SW 97th Ave", "SW 98th Ave", "SW 99th Ave", "SW 100th Ave",
    "SW 101st Ave", "SW 102nd Ave", "SW 103rd Ave", "SW 104th Ave", "SW 105th Ave",
    "NE Alberta St", "NE Fremont St", "NE Prescott St", "NE Killingsworth St",
    "NE Alberta St", "NE Ainsworth St", "NE Beech St", "NE Failing St", "NE Fargo St",
    "NE Going St", "NE Graham St", "NE Hancock St", "NE Humboldt St", "NE Irving St",
    "NE Jarrett St", "NE Klickitat St", "NE Lombard St", "NE Mason St", "NE Prescott St",
    "NE Rodney Ave", "NE Russell St", "NE Sacramento St", "NE Schuyler St", "NE Shaver St",
    "NE Skidmore St", "NE Stanton St", "NE Sumner St", "NE Tillamook St", "NE Union Ave",
    "NE Van Buren St", "NE Wasco St", "NE Webster Ave", "NE Wygant St", "NE 7th Ave",
    "NE 8th Ave", "NE 9th Ave", "NE 10th Ave", "NE 11th Ave", "NE 12th Ave",
    "NE 13th Ave", "NE 14th Ave", "NE 15th Ave", "NE 16th Ave", "NE 17th Ave",
    "NE 18th Ave", "NE 19th Ave", "NE 20th Ave", "NE 21st Ave", "NE 22nd Ave",
    "NE 23rd Ave", "NE 24th Ave", "NE 25th Ave", "NE 26th Ave", "NE 27th Ave",
    "NE 28th Ave", "NE 29th Ave", "NE 30th Ave", "NE 31st Ave", "NE 32nd Ave",
    "NE 33rd Ave", "NE 34th Ave", "NE 35th Ave", "NE 36th Ave", "NE 37th Ave",
    "NE 38th Ave", "NE 39th Ave", "NE 40th Ave", "NE 41st Ave", "NE 42nd Ave",
    "NE 43rd Ave", "NE 44th Ave", "NE 45th Ave", "NE 46th Ave", "NE 47th Ave",
    "NE 48th Ave", "NE 49th Ave", "NE 50th Ave", "NE 51st Ave", "NE 52nd Ave",
    "NE 53rd Ave", "NE 54th Ave", "NE 55th Ave", "NE 56th Ave", "NE 57th Ave",
    "NE 58th Ave", "NE 59th Ave", "NE 60th Ave", "NE 61st Ave", "NE 62nd Ave",
    "NE 63rd Ave", "NE 64th Ave", "NE 65th Ave", "NE 66th Ave", "NE 67th Ave",
    "NE 68th Ave", "NE 69th Ave", "NE 70th Ave", "NE 71st Ave", "NE 72nd Ave",
    "NE 73rd Ave", "NE 74th Ave", "NE 75th Ave", "NE 76th Ave", "NE 77th Ave",
    "NE 78th Ave", "NE 79th Ave", "NE 80th Ave", "NE 81st Ave", "NE 82nd Ave",
    "NE 83rd Ave", "NE 84th Ave", "NE 85th Ave", "NE 86th Ave", "NE 87th Ave",
    "NE 88th Ave", "NE 89th Ave", "NE 90th Ave", "NE 91st Ave", "NE 92nd Ave",
    "NE 93rd Ave", "NE 94th Ave", "NE 95th Ave", "NE 96th Ave", "NE 97th Ave",
    "NE 98th Ave", "NE 99th Ave", "NE 100th Ave", "NE 101st Ave", "NE 102nd Ave",
    "NE 103rd Ave", "NE 104th Ave", "NE 105th Ave", "NE 106th Ave", "NE 107th Ave",
    "NE 108th Ave", "NE 109th Ave", "NE 110th Ave", "NE 111th Ave", "NE 112th Ave",
    "NE 113th Ave", "NE 114th Ave", "NE 115th Ave", "NE 116th Ave", "NE 117th Ave",
    "NE 118th Ave", "NE 119th Ave", "NE 120th Ave", "NE 121st Ave", "NE 122nd Ave",
    "NE 123rd Ave", "NE 124th Ave", "NE 125th Ave", "NE 126th Ave", "NE 127th Ave",
    "NE 128th Ave", "NE 129th Ave", "NE 130th Ave", "NE 131st Ave", "NE 132nd Ave",
    "NE 133rd Ave", "NE 134th Ave", "NE 135th Ave", "NE 136th Ave", "NE 137th Ave",
    "NE 138th Ave", "NE 139th Ave", "NE 140th Ave", "NE 141st Ave", "NE 142nd Ave",
    "NE 143rd Ave", "NE 144th Ave", "NE 145th Ave", "NE 146th Ave", "NE 147th Ave",
    "NE 148th Ave", "NE 149th Ave", "NE 150th Ave", "NE 151st Ave", "NE 152nd Ave",
    "NE 153rd Ave", "NE 154th Ave", "NE 155th Ave", "NE 156th Ave", "NE 157th Ave",
    "NE 158th Ave", "NE 159th Ave", "NE 160th Ave", "NE 161st Ave", "NE 162nd Ave",
    "SE Powell Blvd", "SE Division St", "SE Hawthorne Blvd", "SE Belmont St",
    "SE Morrison St", "SE Yamhill St", "SE Alder St", "SE Washington St",
    "SE Stark St", "SE Oak St", "SE Pine St", "SE Burnside St", "SE Ankeny St",
    "SE Ash St", "SE Pine St", "SE Madison St", "SE Clay St", "SE Market St",
    "SE Mill St", "SE Spokane Ave", "SE 11th Ave", "SE 12th Ave", "SE 13th Ave",
    "SE 14th Ave", "SE 15th Ave", "SE 16th Ave", "SE 17th Ave", "SE 18th Ave",
    "SE 19th Ave", "SE 20th Ave", "SE 21st Ave", "SE 22nd Ave", "SE 23rd Ave",
    "SE 24th Ave", "SE 25th Ave", "SE 26th Ave", "SE 27th Ave", "SE 28th Ave",
    "SE 29th Ave", "SE 30th Ave", "SE 31st Ave", "SE 32nd Ave", "SE 33rd Ave",
    "SE 34th Ave", "SE 35th Ave", "SE 36th Ave", "SE 37th Ave", "SE 38th Ave",
    "SE 39th Ave", "SE 40th Ave", "SE 41st Ave", "SE 42nd Ave", "SE 43rd Ave",
    "SE 44th Ave", "SE 45th Ave", "SE 46th Ave", "SE 47th Ave", "SE 48th Ave",
    "SE 49th Ave", "SE 50th Ave", "SE 51st Ave", "SE 52nd Ave", "SE 53rd Ave",
    "SE 54th Ave", "SE 55th Ave", "SE 56th Ave", "SE 57th Ave", "SE 58th Ave",
    "SE 59th Ave", "SE 60th Ave", "SE 61st Ave", "SE 62nd Ave", "SE 63rd Ave",
    "SE 64th Ave", "SE 65th Ave", "SE 66th Ave", "SE 67th Ave", "SE 68th Ave",
    "SE 69th Ave", "SE 70th Ave", "SE 71st Ave", "SE 72nd Ave", "SE 73rd Ave",
    "SE 74th Ave", "SE 75th Ave", "SE 76th Ave", "SE 77th Ave", "SE 78th Ave",
    "SE 79th Ave", "SE 80th Ave", "SE 81st Ave", "SE 82nd Ave", "SE 83rd Ave",
    "SE 84th Ave", "SE 85th Ave", "SE 86th Ave", "SE 87th Ave", "SE 88th Ave",
    "SE 89th Ave", "SE 90th Ave", "SE 91st Ave", "SE 92nd Ave", "SE 93rd Ave",
    "SE 94th Ave", "SE 95th Ave", "SE 96th Ave", "SE 97th Ave", "SE 98th Ave",
    "SE 99th Ave", "SE 100th Ave", "SE 101st Ave", "SE 102nd Ave", "SE 103rd Ave",
    "SE 104th Ave", "SE 105th Ave", "SE 106th Ave", "SE 107th Ave", "SE 108th Ave",
    "SE 109th Ave", "SE 110th Ave", "SE 111th Ave", "SE 112th Ave", "SE 113th Ave",
    "SE 114th Ave", "SE 115th Ave", "SE 116th Ave", "SE 117th Ave", "SE 118th Ave",
    "SE 119th Ave", "SE 120th Ave", "SE 121st Ave", "SE 122nd Ave", "SE 123rd Ave",
    "SE 124th Ave", "SE 125th Ave", "SE 126th Ave", "SE 127th Ave", "SE 128th Ave",
    "SE 129th Ave", "SE 130th Ave", "SE 131st Ave", "SE 132nd Ave", "SE 133rd Ave",
    "SE 134th Ave", "SE 135th Ave", "SE 136th Ave", "SE 137th Ave", "SE 138th Ave",
    "SE 139th Ave", "SE 140th Ave", "SE 141st Ave", "SE 142nd Ave", "SE 143rd Ave",
    "SE 144th Ave", "SE 145th Ave", "SE 146th Ave", "SE 147th Ave", "SE 148th Ave",
    "SE 149th Ave", "SE 150th Ave", "SE 151st Ave", "SE 152nd Ave", "SE 153rd Ave",
    "SE 154th Ave", "SE 155th Ave", "SE 156th Ave", "SE 157th Ave", "SE 158th Ave",
    "SE 159th Ave", "SE 160th Ave", "SE 161st Ave", "SE 162nd Ave", "SE 163rd Ave",
    "SE 164th Ave", "SE 165th Ave", "SE 166th Ave", "SE 167th Ave", "SE 168th Ave",
    "SE 169th Ave", "SE 170th Ave", "SE 171st Ave", "SE 172nd Ave", "NW 23rd Ave",
    "NW 21st Ave", "NW 22nd Ave", "NW 24th Ave", "NW 25th Ave", "NW Lovejoy St",
    "NW Kearney St", "NW Johnson St", "NW Marshall St", "NW Northrup St",
    "NW Overton St", "NW Pettygrove St", "NW Quimby St", "NW Raleigh St",
    "NW Savier St", "NW Thurman St", "NW Uptown Ter", "NW Vaughn St",
    "NW Wilson St", "NW Yeon Ave", "NW 10th Ave", "NW 11th Ave", "NW 12th Ave",
    "NW 13th Ave", "NW 14th Ave", "NW 15th Ave", "NW 16th Ave", "NW 17th Ave",
    "NW 18th Ave", "NW 19th Ave", "NW 20th Ave", "NW 26th Ave", "NW 27th Ave",
    "NW 28th Ave", "NW 29th Ave", "NW 30th Ave", "NW 31st Ave", "NW 32nd Ave",
    "NW 33rd Ave", "NW 34th Ave", "NW 35th Ave", "NW 36th Ave", "NW 37th Ave",
    "NW 38th Ave", "NW 39th Ave", "NW 40th Ave", "NW 41st Ave", "NW 42nd Ave",
    "NW 43rd Ave", "NW 44th Ave", "NW 45th Ave", "NW 46th Ave", "NW 47th Ave",
    "NW 48th Ave", "NW 49th Ave", "NW 50th Ave", "NW 51st Ave", "NW 52nd Ave",
    "NW 53rd Ave", "NW 54th Ave", "NW 55th Ave", "NW 56th Ave", "NW 57th Ave",
    "NW 58th Ave", "NW 59th Ave", "NW 60th Ave", "NW 61st Ave", "NW 62nd Ave",
    "NW 63rd Ave", "NW 64th Ave", "NW 65th Ave", "NW 66th Ave", "NW 67th Ave",
    "NW 68th Ave", "NW 69th Ave", "NW 70th Ave", "NW 71st Ave", "NW 72nd Ave",
    "NW 73rd Ave", "NW 74th Ave", "NW 75th Ave", "NW 76th Ave", "NW 77th Ave",
    "NW 78th Ave", "NW 79th Ave", "NW 80th Ave", "NW 81st Ave", "NW 82nd Ave",
    "NW 83rd Ave", "NW 84th Ave", "NW 85th Ave", "NW 86th Ave", "NW 87th Ave",
    "NW 88th Ave", "NW 89th Ave", "NW 90th Ave", "NW 91st Ave", "NW 92nd Ave",
    "NW 93rd Ave", "NW 94th Ave", "NW 95th Ave", "NW 96th Ave", "NW 97th Ave",
    "NW 98th Ave", "NW 99th Ave", "NW 100th Ave", "NW 101st Ave", "NW 102nd Ave",
    "NW 103rd Ave", "NW 104th Ave", "NW 105th Ave", "N Williams Ave", "N Vancouver Ave",
    "N Interstate Ave", "N Kerby Ave", "N Albina Ave", "N Mississippi Ave",
    "N Fremont St", "N Cook St", "N Prescott St", "N Killingsworth St",
    "N Alberta St", "N Ainsworth St", "N Emerson St", "N Fenwick St",
    "N Going St", "N Graham St", "N Haight Ave", "N Hamlin Ave",
    "N Haven St", "N Hodge St", "N Hollyrood Ct", "N Humboldt St",
    "N Hurlburt St", "N Ivy St", "N Jarrett St", "N Jessup St",
    "N Kellogg St", "N Klickitat St", "N Lenox St", "N Lombard St",
    "N Madeleine Ave", "N Mason St", "N McClellan St", "N Mohawk Ave",
    "N Montana Ave", "N Newark Ave", "N Ogden St", "N Oswego Ter",
    "N Peninsular Ave", "N Polk Ave", "N Portsmouth Ave", "N Prescott St",
    "N Princeton St", "N Richmond Ave", "N Rosa Parks Way", "N Russet St",
    "N Saratoga St", "N Seneca St", "N Seward St", "N Simpson St",
    "N Skidmore St", "N Smith Ave", "N St Louis Ave", "N Stanford Ave",
    "N Stanton St", "N Sumner St", "N Syracuse St", "N Terry St",
    "N Trenton St", "N Troutdale Rd", "N Tyler Ave", "N Vancouver Ave",
    "N Villard Ave", "N Wall Ave", "N Watts St", "N Willis Blvd",
    "N Willamette Blvd", "N Woolsey Ave", "N Wygant St", "N Yale St",
    "S Macadam Ave", "S Kelly Ave", "S Boundary St", "S Corbett Ave",
    "S Gibbs St", "S Hood Ave", "S Lane St", "S Montgomery St",
    "S Moody Ave", "S River Pkwy", "S Water Ave", "S Bond Ave",
    "S Gaines St", "S Porter St", "S Sherman St", "S Arthur St",
    "S 1st Ave", "S 2nd Ave", "S 3rd Ave", "S 4th Ave", "S 5th Ave",
    "S 6th Ave", "S 7th Ave", "S 8th Ave", "S 9th Ave", "S 10th Ave",
    "S 11th Ave", "S 12th Ave", "S 13th Ave", "S 14th Ave", "S 15th Ave",
    "S 16th Ave", "S 17th Ave", "S 18th Ave", "S 19th Ave", "S 20th Ave",
    "S 21st Ave", "S 22nd Ave", "S 23rd Ave", "S 24th Ave", "S 25th Ave",
    "S 26th Ave", "S 27th Ave", "S 28th Ave", "S 29th Ave", "S 30th Ave",
    "S 31st Ave", "S 32nd Ave", "S 33rd Ave", "S 34th Ave", "S 35th Ave",
    "S 36th Ave", "S 37th Ave", "S 38th Ave", "S 39th Ave", "S 40th Ave",
    "S 41st Ave", "S 42nd Ave", "S 43rd Ave", "S 44th Ave", "S 45th Ave",
    "S 46th Ave", "S 47th Ave", "S 48th Ave", "S 49th Ave", "S 50th Ave",
    "S 51st Ave", "S 52nd Ave", "S 53rd Ave", "S 54th Ave", "S 55th Ave",
    "S 56th Ave", "S 57th Ave", "S 58th Ave", "S 59th Ave", "S 60th Ave",
    "S 61st Ave", "S 62nd Ave", "S 63rd Ave", "S 64th Ave", "S 65th Ave",
    "S 66th Ave", "S 67th Ave", "S 68th Ave", "S 69th Ave", "S 70th Ave",
    "S 71st Ave", "S 72nd Ave", "S 73rd Ave", "S 74th Ave", "S 75th Ave",
    "S 76th Ave", "S 77th Ave", "S 78th Ave", "S 79th Ave", "S 80th Ave",
    "S 81st Ave", "S 82nd Ave", "S 83rd Ave", "S 84th Ave", "S 85th Ave",
    "S 86th Ave", "S 87th Ave", "S 88th Ave", "S 89th Ave", "S 90th Ave",
    "S 91st Ave", "S 92nd Ave", "S 93rd Ave", "S 94th Ave", "S 95th Ave",
    "S 96th Ave", "S 97th Ave", "S 98th Ave", "S 99th Ave", "S 100th Ave",
    "S 101st Ave", "S 102nd Ave", "S 103rd Ave", "S 104th Ave", "S 105th Ave",
    "S 106th Ave", "S 107th Ave", "S 108th Ave", "S 109th Ave", "S 110th Ave",
    "S 111th Ave", "S 112th Ave", "S 113th Ave", "S 114th Ave", "S 115th Ave",
    "S 116th Ave", "S 117th Ave", "S 118th Ave", "S 119th Ave", "S 120th Ave",
    "S 121st Ave", "S 122nd Ave", "S 123rd Ave", "S 124th Ave", "S 125th Ave",
    "S 126th Ave", "S 127th Ave", "S 128th Ave", "S 129th Ave", "S 130th Ave",
    "S 131st Ave", "S 132nd Ave", "S 133rd Ave", "S 134th Ave", "S 135th Ave",
    "S 136th Ave", "S 137th Ave", "S 138th Ave", "S 139th Ave", "S 140th Ave",
    "S 141st Ave", "S 142nd Ave", "S 143rd Ave", "S 144th Ave", "S 145th Ave",
    "S 146th Ave", "S 147th Ave", "S 148th Ave", "S 149th Ave", "S 150th Ave",
    "S 151st Ave", "S 152nd Ave", "S 153rd Ave", "S 154th Ave", "S 155th Ave",
    "S 156th Ave", "S 157th Ave", "S 158th Ave", "S 159th Ave", "S 160th Ave",
    "S 161st Ave", "S 162nd Ave", "S 163rd Ave", "S 164th Ave", "S 165th Ave",
    "S 166th Ave", "S 167th Ave", "S 168th Ave", "S 169th Ave", "S 170th Ave",
    "S 171st Ave", "S 172nd Ave", "S 173rd Ave", "S 174th Ave", "S 175th Ave",
    "S 176th Ave", "S 177th Ave", "S 178th Ave", "S 179th Ave", "S 180th Ave",
    "S 181st Ave", "S 182nd Ave", "S 183rd Ave", "S 184th Ave", "S 185th Ave",
    "S 186th Ave", "S 187th Ave", "S 188th Ave", "S 189th Ave", "S 190th Ave",
    "S 191st Ave", "S 192nd Ave", "S 193rd Ave", "S 194th Ave", "S 195th Ave",
    "S 196th Ave", "S 197th Ave", "S 198th Ave", "S 199th Ave", "S 200th Ave",
    "E Burnside St", "E Couch St", "E Davis St", "E Burnside St", "E Morrison St",
    "E Yamhill St", "E Alder St", "E Washington St", "E Stark St", "E Oak St",
    "E Pine St", "E Ankeny St", "E Ash St", "E Pine St", "E Madison St",
    "E Clay St", "E Market St", "E Mill St", "E Burnside St", "E Couch St",
    "E Davis St", "E Burnside St", "E Morrison St", "E Yamhill St", "E Alder St",
    "E Washington St", "E Stark St", "E Oak St", "E Pine St", "E Ankeny St",
    "E Ash St", "E Pine St", "E Madison St", "E Clay St", "E Market St",
    "E Mill St", "E Burnside St", "E Couch St", "E Davis St", "E Burnside St",
    "E Morrison St", "E Yamhill St", "E Alder St", "E Washington St", "E Stark St",
    "E Oak St", "E Pine St", "E Ankeny St", "E Ash St", "E Pine St",
    "E Madison St", "E Clay St", "E Market St", "E Mill St", "E Burnside St",
    "E Couch St", "E Davis St", "E Burnside St", "E Morrison St", "E Yamhill St",
    "E Alder St", "E Washington St", "E Stark St", "E Oak St", "E Pine St",
    "E Ankeny St", "E Ash St", "E Pine St", "E Madison St", "E Clay St",
    "E Market St", "E Mill St", "E Burnside St", "E Couch St", "E Davis St",
    "E Burnside St", "E Morrison St", "E Yamhill St", "E Alder St", "E Washington St",
    "E Stark St", "E Oak St", "E Pine St", "E Ankeny St", "E Ash St",
    "E Pine St", "E Madison St", "E Clay St", "E Market St", "E Mill St",
    "W Burnside St", "W Couch St", "W Davis St", "W Burnside St", "W Morrison St",
    "W Yamhill St", "W Alder St", "W Washington St", "W Stark St", "W Oak St",
    "W Pine St", "W Ankeny St", "W Ash St", "W Pine St", "W Madison St",
    "W Clay St", "W Market St", "W Mill St", "W Burnside St", "W Couch St",
    "W Davis St", "W Burnside St", "W Morrison St", "W Yamhill St", "W Alder St",
    "W Washington St", "W Stark St", "W Oak St", "W Pine St", "W Ankeny St",
    "W Ash St", "W Pine St", "W Madison St", "W Clay St", "W Market St",
    "W Mill St", "N Lombard St", "N Chautauqua Blvd", "N Portsmouth Ave",
    "N Greely Ave", "N Fessenden St", "N Willis Blvd", "N Richmond Ave",
    "N Hodge St", "N Central St", "N Houghton St", "N Midway Ave",
    "N Geneva Ave", "N Halsey St", "N Wygant St", "N Holman St",
    "N Montana Ave", "N Foss Ave", "N Hodge St", "N Willis Blvd",
    "N Richmond Ave", "N Hodge St", "N Central St", "N Houghton St",
    "N Midway Ave", "N Geneva Ave", "N Halsey St", "N Wygant St",
    "N Holman St", "N Montana Ave", "N Foss Ave", "N Hodge St",
    "N Willis Blvd", "N Richmond Ave", "N Hodge St", "N Central St",
    "N Houghton St", "N Midway Ave", "N Geneva Ave", "N Halsey St",
    "N Wygant St", "N Holman St", "N Montana Ave", "N Foss Ave",
    "N Hodge St", "N Willis Blvd", "N Richmond Ave", "N Hodge St",
    "N Central St", "N Houghton St", "N Midway Ave", "N Geneva Ave",
    "N Halsey St", "N Wygant St", "N Holman St", "N Montana Ave",
    "N Foss Ave", "N Hodge St", "N Willis Blvd", "N Richmond Ave"
];

// Export the arrays so they can be imported by other files
module.exports = {
    FIRST_NAMES,
    LAST_NAMES,
    STREET_NAMES
};